# Generated by Django 4.1.4 on 2023-02-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='number',
        ),
    ]
