# Generated by Django 4.1.4 on 2023-03-03 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_like_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_liked',
            field=models.ManyToManyField(default=0, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
