# Generated by Django 4.1.4 on 2023-03-03 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_users_liked_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_liked',
            field=models.ManyToManyField(related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
